pipeline{

    
    
    agent {
        label "master"
        /*docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }*/
    }
   
    stages {
        
        stage('Build') {
            steps {
                sh 'echo hello'
                //sh 'mvn -B -DskipTests clean package'
                
            }
        }
        stage('Test') {
            steps {
                echo 'echo hello'
                //sh 'mvn test'
                
            }
            post {
                always {
                    echo 'echo hello'
                    //junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Snyk'){
            
            steps{
                
                snykSecurity projectName: 'sneak-pipeline-test', snykInstallation: 'SnykPluginTest', snykTokenId: 'snyktoken'
                withCredentials([string(credentialsId: 'snyktkn', variable: 'SNYK_TOKEN')]) {
                    sh '''
                    set +e
                    docker build -t myapp:latest Dockerfile
                    snyk auth ${SNYK_TOKEN}
                    snyk container test myapp:latest --json --file=Dockerfile --project-name=docker-check-cli
                    '''
                }
            }
        }
       
        /*stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }*/
    }
 
}
