pipeline{

    
    
    agent {
        label "master"
        /*docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }*/
    }
   
    stages {
        
        stage('Build') {
            steps {
                
                sh 'mvn -B -DskipTests clean package'
                
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Snyk'){
            environment {
                    SNYK_TOKEN = credentials('snyktoken')
                }
            steps{
                
                snykSecurity projectName: 'sneak-pipeline-test', snykInstallation: 'SnykPluginTest', snykTokenId: 'snyktoken'
                sh """
                snyk auth ${SNYK_TOKEN}
                snyk container test --json --file=Dockerfile --project-name=docker-check
                """
            }
        }
       
        /*stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }*/
    }
 
}
